# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [39]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [40]:
A = np.arange(1, 16).reshape(3,5)
dim = A.ndim
shape = A.shape
size = A.size
dtype = A.dtype

print("Dimension:", dim)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)



Dimension: 2
Shape: (3, 5)
Size: 15
Data type: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [41]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

sub = B - C
mult = B * C
matmult = B @ C

print(B)
print()
print(C)
print()
print(sub)
print()
print(mult)
print()
print(matmult)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [42]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()

B_exp = np.exp(B)
print(B_exp)

min_value = np.min(B_exp)
print()
print(min_value)

min_value_row = np.min (B_exp, axis=1)
print()
print(min_value_row)

min_value_col = np.min (B_exp, axis=0)
print()
print(min_value_col)

min_index = np.argmin(B_exp)
print()
print(min_index)

min_index_row = np.argmin (B_exp, axis=1)
print()
print(min_index_row)

total_sum = np.sum(B_exp)
print()
print(total_sum)

mean_col = np.mean(B_exp, axis=0)
print()
print(mean_col)

print()

median_col =  np.median(B_exp, axis=0)
print(median_col)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

2.718281828459045

[   2.71828183   54.59815003 1096.63315843]

[ 2.71828183  7.3890561  20.08553692]

0

[0 0 0]

12817.308050524603

[ 384.64986343 1045.58673408 2842.19941933]

[ 54.59815003 148.4131591  403.42879349]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [43]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [44]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [45]:
# If we provide fewer indices than axes in numpy, it fills in the missing indices with colon, which selects all the elements in the dimension. If we want to specify all elements we can use colon like A[1,:]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [46]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [48]:
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

for row in A:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [49]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [50]:
# The first line creates a one dimensional "a" array with values between 0 to 29.
# The second line reshapes the "a" array into a third dimensional array "b" with the shape 2, 3, -1.
# The first dimension 2 says there will be two blocks. The second dimension 3, says each block has 3 rows. The third dimension -1 is then calculated by NumPy automatically.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [51]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [52]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [53]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

# Vector- and matrix algebra Exercises

In [54]:
def add_mult_matrices(A, B, add_mult):
    A = np.array(A)
    B = np.array(B)
    
    if not isinstance(A, np.ndarray):
        return "Input is not a numpy array."
    if not isinstance (B, np.ndarray):
        return "Input is not a numpy array."
    
    if add_mult == "add" and A.shape != B.shape:
        print("Matrices are not of equal size.")
    elif add_mult == "add":
        return A + B
    elif add_mult == "multiply" and A.shape[1] != B.shape[0]:
        return "Number of columns are not equal."
    elif add_mult == "multiply":
        return A @ B
    else:
        return "Choose 'add' or 'multiply'"

A = [[1, 2], [3, 4]]
B = [[2, 3], [4, 5]]
add_mult = "add"

print(add_mult_matrices(A, B, add_mult))

[[3 5]
 [7 9]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [55]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

print("v1 base:", v1.base)
print("v2 base:", v2.base )  # Same outcome as v1, v2 is a view of v1.

v2[-1] = 123
print()
print(v1)
print(v2) # If changes are made to the view (v2 in this code) it also affects the original (v1) and vice versa. If v2 was a copy it wouldnät affect v1.

[0 1 2 3]
[2 3]
v1 base: None
v2 base: [0 1 2 3]

[  0   1   2 123]
[  2 123]


In [56]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [57]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
